# Generated by Django 6.0.5 on 2026-05-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла картинки'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фото'),
        ),
    ]
