# Generated by Django 6.0.5 on 2026-06-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0004_pizza_image_name_alter_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла картинки'),
        ),
    ]
